const radicals = [
    { char: '一', meaning: 'one', strokes: 1, reading: 'ichi' },
    { char: '丨', meaning: 'line', strokes: 1, reading: 'bou' },
    { char: '丶', meaning: 'dot', strokes: 1, reading: 'ten' },
    { char: '丿', meaning: 'slash', strokes: 1, reading: 'no' },
    { char: '乙', meaning: 'second', strokes: 1, reading: 'otsu' },
    { char: '亅', meaning: 'hook', strokes: 1, reading: 'kagi' },
    { char: '二', meaning: 'two', strokes: 2, reading: 'ni' },
    { char: '亠', meaning: 'lid', strokes: 2, reading: 'nabebuta' },
    { char: '人', meaning: 'person', strokes: 2, reading: 'hito' },
    { char: '儿', meaning: 'legs', strokes: 2, reading: 'ninnyou' },
    { char: '入', meaning: 'enter', strokes: 2, reading: 'iru' },
    { char: '八', meaning: 'eight', strokes: 2, reading: 'hachi' },
    { char: '冂', meaning: 'upside-down box', strokes: 2, reading: 'keigamae' },
    { char: '冖', meaning: 'cover', strokes: 2, reading: 'wakammuri' },
    { char: '冫', meaning: 'ice', strokes: 2, reading: 'nisui' },
    { char: '几', meaning: 'table', strokes: 2, reading: 'kisu' },
    { char: '凵', meaning: 'container', strokes: 2, reading: 'kannyou' },
    { char: '刀', meaning: 'sword', strokes: 2, reading: 'katana' },
    { char: '力', meaning: 'power', strokes: 2, reading: 'chikara' },
    { char: '勹', meaning: 'wrap', strokes: 2, reading: 'tsutsumigamae' },
    { char: '匕', meaning: 'spoon', strokes: 2, reading: 'saji' },
    { char: '匚', meaning: 'box', strokes: 2, reading: 'hakogamae' },
    { char: '匸', meaning: 'hiding enclosure', strokes: 2, reading: 'kakushigamae' },
    { char: '十', meaning: 'ten', strokes: 2, reading: 'juu' },
    { char: '卜', meaning: 'divination', strokes: 2, reading: 'boku' },
    { char: '卩', meaning: 'seal', strokes: 2, reading: 'fushizukuri' },
    { char: '厂', meaning: 'cliff', strokes: 2, reading: 'gandare' },
    { char: '厶', meaning: 'private', strokes: 2, reading: 'mu' },
    { char: '又', meaning: 'again', strokes: 2, reading: 'mata' },
    { char: '口', meaning: 'mouth', strokes: 3, reading: 'kuchi' },
    { char: '囗', meaning: 'enclosure', strokes: 3, reading: 'kunigamae' },
    { char: '土', meaning: 'earth', strokes: 3, reading: 'tsuchi' },
    { char: '士', meaning: 'scholar', strokes: 3, reading: 'samurai' },
    { char: '夂', meaning: 'winter', strokes: 3, reading: 'fuyugashira' },
    { char: '夊', meaning: 'winter variant', strokes: 3, reading: 'suinyou' },
    { char: '夕', meaning: 'evening', strokes: 3, reading: 'yuube' },
    { char: '大', meaning: 'big', strokes: 3, reading: 'dai' },
    { char: '女', meaning: 'woman', strokes: 3, reading: 'onna' },
    { char: '子', meaning: 'child', strokes: 3, reading: 'ko' },
    { char: '宀', meaning: 'roof', strokes: 3, reading: 'ukammuri' },
    { char: '寸', meaning: 'inch', strokes: 3, reading: 'sun' },
    { char: '小', meaning: 'small', strokes: 3, reading: 'shou' },
    { char: '尢', meaning: 'lame', strokes: 3, reading: 'dainomageashi' },
    { char: '尸', meaning: 'corpse', strokes: 3, reading: 'shikabane' },
    { char: '屮', meaning: 'sprout', strokes: 3, reading: 'tetsu' },
    { char: '山', meaning: 'mountain', strokes: 3, reading: 'yama' },
    { char: '巛', meaning: 'river', strokes: 3, reading: 'magarikawa' },
    { char: '工', meaning: 'work', strokes: 3, reading: 'takumi' },
    { char: '己', meaning: 'self', strokes: 3, reading: 'onore' },
    { char: '巾', meaning: 'turban', strokes: 3, reading: 'haba' },
    { char: '干', meaning: 'dry', strokes: 3, reading: 'kan' },
    { char: '幺', meaning: 'short thread', strokes: 3, reading: 'you' },
    { char: '广', meaning: 'dotted cliff', strokes: 3, reading: 'madare' },
    { char: '廴', meaning: 'long stride', strokes: 3, reading: 'ennyou' },
    { char: '廾', meaning: 'two hands', strokes: 3, reading: 'nijuuashi' },
    { char: '弋', meaning: 'shoot', strokes: 3, reading: 'shikigamae' },
    { char: '弓', meaning: 'bow', strokes: 3, reading: 'yumi' },
    { char: '彐', meaning: 'snout', strokes: 3, reading: 'keigashira' },
    { char: '彡', meaning: 'bristle', strokes: 3, reading: 'sanzukuri' },
    { char: '彳', meaning: 'step', strokes: 3, reading: 'gyouninben' },
    { char: '心', meaning: 'heart', strokes: 4, reading: 'kokoro' },
    { char: '戈', meaning: 'halberd', strokes: 4, reading: 'hoko' },
    { char: '戸', meaning: 'door', strokes: 4, reading: 'to' },
    { char: '手', meaning: 'hand', strokes: 4, reading: 'te' },
    { char: '支', meaning: 'branch', strokes: 4, reading: 'shinyou' },
    { char: '攴', meaning: 'rap', strokes: 4, reading: 'bokuzukuri' },
    { char: '文', meaning: 'script', strokes: 4, reading: 'bun' },
    { char: '斗', meaning: 'dipper', strokes: 4, reading: 'tomasu' },
    { char: '斤', meaning: 'axe', strokes: 4, reading: 'ono' },
    { char: '方', meaning: 'square', strokes: 4, reading: 'hou' },
    { char: '无', meaning: 'not', strokes: 4, reading: 'munyou' },
    { char: '日', meaning: 'sun', strokes: 4, reading: 'hi' },
    { char: '曰', meaning: 'say', strokes: 4, reading: 'hirabi' },
    { char: '月', meaning: 'moon', strokes: 4, reading: 'tsuki' },
    { char: '木', meaning: 'tree', strokes: 4, reading: 'ki' },
    { char: '欠', meaning: 'lack', strokes: 4, reading: 'akubi' },
    { char: '止', meaning: 'stop', strokes: 4, reading: 'tomeru' },
    { char: '歹', meaning: 'death', strokes: 4, reading: 'gatsuhen' },
    { char: '殳', meaning: 'weapon', strokes: 4, reading: 'rumata' },
    { char: '毋', meaning: 'do not', strokes: 4, reading: 'nakare' },
    { char: '比', meaning: 'compare', strokes: 4, reading: 'kuraberu' },
    { char: '毛', meaning: 'fur', strokes: 4, reading: 'ke' },
    { char: '氏', meaning: 'clan', strokes: 4, reading: 'uji' },
    { char: '气', meaning: 'steam', strokes: 4, reading: 'kigamae' },
    { char: '水', meaning: 'water', strokes: 4, reading: 'mizu' },
    { char: '火', meaning: 'fire', strokes: 4, reading: 'hi' },
    { char: '爪', meaning: 'claw', strokes: 4, reading: 'tsume' },
    { char: '父', meaning: 'father', strokes: 4, reading: 'chichi' },
    { char: '爻', meaning: 'mix', strokes: 4, reading: 'kou' },
    { char: '爿', meaning: 'split wood', strokes: 4, reading: 'shouhen' },
    { char: '片', meaning: 'slice', strokes: 4, reading: 'kata' },
    { char: '牙', meaning: 'fang', strokes: 4, reading: 'kiba' },
    { char: '牛', meaning: 'cow', strokes: 4, reading: 'ushi' },
    { char: '犬', meaning: 'dog', strokes: 4, reading: 'inu' }
];
