const radicals = [
    { char: '一', meaning: 'one', meaningTR: 'bir', strokes: 1, reading: 'ichi' },
    { char: '丨', meaning: 'line', meaningTR: 'çizgi', strokes: 1, reading: 'bou' },
    { char: '丶', meaning: 'dot', meaningTR: 'nokta', strokes: 1, reading: 'ten' },
    { char: '丿', meaning: 'slash', meaningTR: 'eğik çizgi', strokes: 1, reading: 'no' },
    { char: '乙', meaning: 'second', meaningTR: 'ikinci', strokes: 1, reading: 'otsu' },
    { char: '亅', meaning: 'hook', meaningTR: 'kanca', strokes: 1, reading: 'kagi' },
    { char: '二', meaning: 'two', meaningTR: 'iki', strokes: 2, reading: 'ni' },
    { char: '亠', meaning: 'lid', meaningTR: 'kapak', strokes: 2, reading: 'nabebuta' },
    { char: '人', meaning: 'person', meaningTR: 'insan', strokes: 2, reading: 'hito' },
    { char: '儿', meaning: 'legs', meaningTR: 'bacaklar', strokes: 2, reading: 'ninnyou' },
    { char: '入', meaning: 'enter', meaningTR: 'girmek', strokes: 2, reading: 'iru' },
    { char: '八', meaning: 'eight', meaningTR: 'sekiz', strokes: 2, reading: 'hachi' },
    { char: '冂', meaning: 'upside-down box', meaningTR: 'ters kutu', strokes: 2, reading: 'keigamae' },
    { char: '冖', meaning: 'cover', meaningTR: 'örtü', strokes: 2, reading: 'wakammuri' },
    { char: '冫', meaning: 'ice', meaningTR: 'buz', strokes: 2, reading: 'nisui' },
    { char: '几', meaning: 'table', meaningTR: 'masa', strokes: 2, reading: 'kisu' },
    { char: '凵', meaning: 'container', meaningTR: 'kap', strokes: 2, reading: 'kannyou' },
    { char: '刀', meaning: 'sword', meaningTR: 'kılıç', strokes: 2, reading: 'katana' },
    { char: '力', meaning: 'power', meaningTR: 'güç', strokes: 2, reading: 'chikara' },
    { char: '勹', meaning: 'wrap', meaningTR: 'sarmak', strokes: 2, reading: 'tsutsumigamae' },
    { char: '匕', meaning: 'spoon', meaningTR: 'kaşık', strokes: 2, reading: 'saji' },
    { char: '匚', meaning: 'box', meaningTR: 'kutu', strokes: 2, reading: 'hakogamae' },
    { char: '匸', meaning: 'hiding enclosure', meaningTR: 'gizleme', strokes: 2, reading: 'kakushigamae' },
    { char: '十', meaning: 'ten', meaningTR: 'on', strokes: 2, reading: 'juu' },
    { char: '卜', meaning: 'divination', meaningTR: 'kehanet', strokes: 2, reading: 'boku' },
    { char: '卩', meaning: 'seal', meaningTR: 'mühür', strokes: 2, reading: 'fushizukuri' },
    { char: '厂', meaning: 'cliff', meaningTR: 'uçurum', strokes: 2, reading: 'gandare' },
    { char: '厶', meaning: 'private', meaningTR: 'özel', strokes: 2, reading: 'mu' },
    { char: '又', meaning: 'again', meaningTR: 'tekrar', strokes: 2, reading: 'mata' },
    { char: '口', meaning: 'mouth', meaningTR: 'ağız', strokes: 3, reading: 'kuchi' },
    { char: '囗', meaning: 'enclosure', meaningTR: 'çevreleme', strokes: 3, reading: 'kunigamae' },
    { char: '土', meaning: 'earth', meaningTR: 'toprak', strokes: 3, reading: 'tsuchi' },
    { char: '士', meaning: 'scholar', meaningTR: 'bilgin', strokes: 3, reading: 'samurai' },
    { char: '夂', meaning: 'winter', meaningTR: 'kış', strokes: 3, reading: 'fuyugashira' },
    { char: '夊', meaning: 'winter variant', meaningTR: 'kış varyantı', strokes: 3, reading: 'suinyou' },
    { char: '夕', meaning: 'evening', meaningTR: 'akşam', strokes: 3, reading: 'yuube' },
    { char: '大', meaning: 'big', meaningTR: 'büyük', strokes: 3, reading: 'dai' },
    { char: '女', meaning: 'woman', meaningTR: 'kadın', strokes: 3, reading: 'onna' },
    { char: '子', meaning: 'child', meaningTR: 'çocuk', strokes: 3, reading: 'ko' },
    { char: '宀', meaning: 'roof', meaningTR: 'çatı', strokes: 3, reading: 'ukammuri' },
    { char: '寸', meaning: 'inch', meaningTR: 'inç', strokes: 3, reading: 'sun' },
    { char: '小', meaning: 'small', meaningTR: 'küçük', strokes: 3, reading: 'shou' },
    { char: '尢', meaning: 'lame', meaningTR: 'topal', strokes: 3, reading: 'dainomageashi' },
    { char: '尸', meaning: 'corpse', meaningTR: 'ceset', strokes: 3, reading: 'shikabane' },
    { char: '屮', meaning: 'sprout', meaningTR: 'filiz', strokes: 3, reading: 'tetsu' },
    { char: '山', meaning: 'mountain', meaningTR: 'dağ', strokes: 3, reading: 'yama' },
    { char: '巛', meaning: 'river', meaningTR: 'nehir', strokes: 3, reading: 'magarikawa' },
    { char: '工', meaning: 'work', meaningTR: 'iş', strokes: 3, reading: 'takumi' },
    { char: '己', meaning: 'self', meaningTR: 'kendi', strokes: 3, reading: 'onore' },
    { char: '巾', meaning: 'turban', meaningTR: 'türban', strokes: 3, reading: 'haba' },
    { char: '干', meaning: 'dry', meaningTR: 'kuru', strokes: 3, reading: 'kan' },
    { char: '幺', meaning: 'short thread', meaningTR: 'kısa iplik', strokes: 3, reading: 'you' },
    { char: '广', meaning: 'dotted cliff', meaningTR: 'noktalı uçurum', strokes: 3, reading: 'madare' },
    { char: '廴', meaning: 'long stride', meaningTR: 'uzun adım', strokes: 3, reading: 'ennyou' },
    { char: '廾', meaning: 'two hands', meaningTR: 'iki el', strokes: 3, reading: 'nijuuashi' },
    { char: '弋', meaning: 'shoot', meaningTR: 'atış', strokes: 3, reading: 'shikigamae' },
    { char: '弓', meaning: 'bow', meaningTR: 'yay', strokes: 3, reading: 'yumi' },
    { char: '彐', meaning: 'snout', meaningTR: 'burun', strokes: 3, reading: 'keigashira' },
    { char: '彡', meaning: 'bristle', meaningTR: 'kıl', strokes: 3, reading: 'sanzukuri' },
    { char: '彳', meaning: 'step', meaningTR: 'adım', strokes: 3, reading: 'gyouninben' },
    { char: '心', meaning: 'heart', meaningTR: 'kalp', strokes: 4, reading: 'kokoro' },
    { char: '戈', meaning: 'halberd', meaningTR: 'mızrak', strokes: 4, reading: 'hoko' },
    { char: '戸', meaning: 'door', meaningTR: 'kapı', strokes: 4, reading: 'to' },
    { char: '手', meaning: 'hand', meaningTR: 'el', strokes: 4, reading: 'te' },
    { char: '支', meaning: 'branch', meaningTR: 'dal', strokes: 4, reading: 'shinyou' },
    { char: '攴', meaning: 'rap', meaningTR: 'vurmak', strokes: 4, reading: 'bokuzukuri' },
    { char: '文', meaning: 'script', meaningTR: 'yazı', strokes: 4, reading: 'bun' },
    { char: '斗', meaning: 'dipper', meaningTR: 'kepçe', strokes: 4, reading: 'tomasu' },
    { char: '斤', meaning: 'axe', meaningTR: 'balta', strokes: 4, reading: 'ono' },
    { char: '方', meaning: 'square', meaningTR: 'kare', strokes: 4, reading: 'hou' },
    { char: '无', meaning: 'not', meaningTR: 'değil', strokes: 4, reading: 'munyou' },
    { char: '日', meaning: 'sun', meaningTR: 'güneş', strokes: 4, reading: 'hi' },
    { char: '曰', meaning: 'say', meaningTR: 'söylemek', strokes: 4, reading: 'hirabi' },
    { char: '月', meaning: 'moon', meaningTR: 'ay', strokes: 4, reading: 'tsuki' },
    { char: '木', meaning: 'tree', meaningTR: 'ağaç', strokes: 4, reading: 'ki' },
    { char: '欠', meaning: 'lack', meaningTR: 'eksiklik', strokes: 4, reading: 'akubi' },
    { char: '止', meaning: 'stop', meaningTR: 'durmak', strokes: 4, reading: 'tomeru' },
    { char: '歹', meaning: 'death', meaningTR: 'ölüm', strokes: 4, reading: 'gatsuhen' },
    { char: '殳', meaning: 'weapon', meaningTR: 'silah', strokes: 4, reading: 'rumata' },
    { char: '毋', meaning: 'do not', meaningTR: 'yapma', strokes: 4, reading: 'nakare' },
    { char: '比', meaning: 'compare', meaningTR: 'karşılaştırmak', strokes: 4, reading: 'kuraberu' },
    { char: '毛', meaning: 'fur', meaningTR: 'kürk', strokes: 4, reading: 'ke' },
    { char: '氏', meaning: 'clan', meaningTR: 'klan', strokes: 4, reading: 'uji' },
    { char: '气', meaning: 'steam', meaningTR: 'buhar', strokes: 4, reading: 'kigamae' },
    { char: '水', meaning: 'water', meaningTR: 'su', strokes: 4, reading: 'mizu' },
    { char: '火', meaning: 'fire', meaningTR: 'ateş', strokes: 4, reading: 'hi' },
    { char: '爪', meaning: 'claw', meaningTR: 'pençe', strokes: 4, reading: 'tsume' },
    { char: '父', meaning: 'father', meaningTR: 'baba', strokes: 4, reading: 'chichi' },
    { char: '爻', meaning: 'mix', meaningTR: 'karıştırmak', strokes: 4, reading: 'kou' },
    { char: '爿', meaning: 'split wood', meaningTR: 'yarık odun', strokes: 4, reading: 'shouhen' },
    { char: '片', meaning: 'slice', meaningTR: 'dilim', strokes: 4, reading: 'kata' },
    { char: '牙', meaning: 'fang', meaningTR: 'diş', strokes: 4, reading: 'kiba' },
    { char: '牛', meaning: 'cow', meaningTR: 'inek', strokes: 4, reading: 'ushi' },
    { char: '犬', meaning: 'dog', meaningTR: 'köpek', strokes: 4, reading: 'inu' }
];
