const radicals = [
    // 1 stroke
    { char: '一', meaning: 'one', meaningTR: 'bir', image: 'minimages/one.png', strokes: 1, reading: 'ichi' },
    { char: '丨', meaning: 'line', meaningTR: 'çizgi', image: 'minimages/line.png', strokes: 1, reading: 'bō' },
    { char: '丶', meaning: 'dot', meaningTR: 'nokta', image: 'minimages/dot.png', strokes: 1, reading: 'ten' },
    { char: '丿', meaning: 'slash', meaningTR: 'eğik çizgi', image: 'minimages/slash.png', strokes: 1, reading: 'no' },
    { char: '乙', meaning: 'second', meaningTR: 'ikinci', image: 'minimages/second.png', strokes: 1, reading: 'otsu' },
    { char: '亅', meaning: 'hook', meaningTR: 'kanca', image: 'minimages/hook.png', strokes: 1, reading: 'hane' },

    // 2 strokes
    { char: '二', meaning: 'two', meaningTR: 'iki', image: 'minimages/two.png', strokes: 2, reading: 'ni' },
    { char: '亠', meaning: 'lid', meaningTR: 'kapak', image: 'minimages/lid.png', strokes: 2, reading: 'nabebuta' },
    { char: '人', meaning: 'person', meaningTR: 'insan', image: 'minimages/person.png', strokes: 2, reading: 'hito' },
    { char: '儿', meaning: 'legs', meaningTR: 'bacaklar', image: 'minimages/legs.png', strokes: 2, reading: 'hitoashi' },
    { char: '入', meaning: 'enter', meaningTR: 'girmek', image: 'minimages/enter.png', strokes: 2, reading: 'iru' },
    { char: '八', meaning: 'eight', meaningTR: 'sekiz', image: 'minimages/eight.png', strokes: 2, reading: 'hachi' },
    { char: '冂', meaning: 'down box', meaningTR: 'açık kutu', image: 'minimages/down.png', strokes: 2, reading: 'keigamae' },
    { char: '冖', meaning: 'cover', meaningTR: 'örtü', image: 'minimages/cover.png', strokes: 2, reading: 'ukanmuri' },
    { char: '冫', meaning: 'ice', meaningTR: 'buz', image: 'minimages/ice.png', strokes: 2, reading: 'nisui' },
    { char: '几', meaning: 'table', meaningTR: 'masa', image: 'minimages/table.png', strokes: 2, reading: 'kinyou' },
    { char: '凵', meaning: 'container', meaningTR: 'kap', image: 'minimages/container.png', strokes: 2, reading: 'kannyou' },
    { char: '刀', meaning: 'knife, sword', meaningTR: 'bıçak, kılıç', image: 'minimages/knife.png', strokes: 2, reading: 'katana' },
    { char: '力', meaning: 'power', meaningTR: 'güç', image: 'minimages/power.png', strokes: 2, reading: 'chikara' },
    { char: '勹', meaning: 'wrap', meaningTR: 'sarmak', image: 'minimages/wrap.png', strokes: 2, reading: 'tsutsumigamae' },
    { char: '匕', meaning: 'spoon', meaningTR: 'kaşık', image: 'minimages/spoon.png', strokes: 2, reading: 'saji' },
    { char: '匚', meaning: 'box', meaningTR: 'kutu', image: 'minimages/box.png', strokes: 2, reading: 'hakogamae' },
    { char: '匸', meaning: 'hide', meaningTR: 'gizleme', image: 'minimages/hide.png', strokes: 2, reading: 'kakushigamae' },
    { char: '十', meaning: 'ten', meaningTR: 'on', image: 'minimages/ten.png', strokes: 2, reading: 'jū' },
    { char: '卜', meaning: 'divination', meaningTR: 'kehanet', image: 'minimages/divination.png', strokes: 2, reading: 'boku' },
    { char: '卩', meaning: 'seal', meaningTR: 'mühür', image: 'minimages/seal.png', strokes: 2, reading: 'fushizukuri' },
    { char: '厂', meaning: 'cliff', meaningTR: 'uçurum', image: 'minimages/cliff.png', strokes: 2, reading: 'gandare' },
    { char: '厶', meaning: 'private', meaningTR: 'özel', image: 'minimages/private.png', strokes: 2, reading: 'mu' },
    { char: '又', meaning: 'again', meaningTR: 'tekrar', image: 'minimages/again.png', strokes: 2, reading: 'mata' },

    // 3 strokes
    { char: '口', meaning: 'mouth', meaningTR: 'ağız', image: 'minimages/mouth.png', strokes: 3, reading: 'kuchi' },
    { char: '囗', meaning: 'enclosure', meaningTR: 'çevreleme', image: 'minimages/enclosure.png', strokes: 3, reading: 'kunigamae' },
    { char: '土', meaning: 'earth', meaningTR: 'toprak', image: 'minimages/earth.png', strokes: 3, reading: 'tsuchi' },
    { char: '士', meaning: 'scholar, samurai', meaningTR: 'bilgin, samuray', image: 'minimages/scholar.png', strokes: 3, reading: 'shi' },
    { char: '夂', meaning: 'go slowly', meaningTR: 'yavaş gitmek', image: 'minimages/go.png', strokes: 3, reading: 'sui' },
    { char: '夊', meaning: 'go slowly (variant)', meaningTR: 'yavaş gitmek (varyant)', image: 'minimages/go.png', strokes: 3, reading: 'suinyō' },
    { char: '夕', meaning: 'evening', meaningTR: 'akşam', image: 'minimages/evening.png', strokes: 3, reading: 'yū' },
    { char: '大', meaning: 'big', meaningTR: 'büyük', image: 'minimages/big.png', strokes: 3, reading: 'dai' },
    { char: '女', meaning: 'woman', meaningTR: 'kadın', image: 'minimages/woman.png', strokes: 3, reading: 'onna' },
    { char: '子', meaning: 'child', meaningTR: 'çocuk', image: 'minimages/child.png', strokes: 3, reading: 'ko' },
    { char: '宀', meaning: 'roof', meaningTR: 'çatı', image: 'minimages/roof.png', strokes: 3, reading: 'ukanmuri' },
    { char: '寸', meaning: 'inch', meaningTR: 'inç', image: 'minimages/inch.png', strokes: 3, reading: 'sun' },
    { char: '小', meaning: 'small', meaningTR: 'küçük', image: 'minimages/small.png', strokes: 3, reading: 'shō' },
    { char: '尢', meaning: 'lame', meaningTR: 'topal', image: 'minimages/lame.png', strokes: 3, reading: 'dainomageashi' },
    { char: '尸', meaning: 'corpse', meaningTR: 'ceset', image: 'minimages/corpse.png', strokes: 3, reading: 'shikabane' },
    { char: '屮', meaning: 'sprout', meaningTR: 'filiz', image: 'minimages/sprout.png', strokes: 3, reading: 'tetsu' },
    { char: '山', meaning: 'mountain', meaningTR: 'dağ', image: 'minimages/mountain.png', strokes: 3, reading: 'yama' },
    { char: '川', meaning: 'river', meaningTR: 'nehir', image: 'minimages/river.png', strokes: 3, reading: 'kawa' },
    { char: '工', meaning: 'work', meaningTR: 'iş', image: 'minimages/work.png', strokes: 3, reading: 'takumi' },
    { char: '己', meaning: 'self', meaningTR: 'kendi', image: 'minimages/self.png', strokes: 3, reading: 'onore' },
    { char: '巾', meaning: 'cloth', meaningTR: 'bez', image: 'minimages/cloth.png', strokes: 3, reading: 'haba' },
    { char: '干', meaning: 'dry', meaningTR: 'kuru', image: 'minimages/dry.png', strokes: 3, reading: 'kan' },
    { char: '幺', meaning: 'short thread', meaningTR: 'kısa iplik', image: 'minimages/short.png', strokes: 3, reading: 'yō' },
    { char: '广', meaning: 'shelter', meaningTR: 'çatı, sığınak', image: 'minimages/shelter.png', strokes: 3, reading: 'madare' },
    { char: '廴', meaning: 'long stride', meaningTR: 'uzun adım', image: 'minimages/long.png', strokes: 3, reading: 'ennyō' },
    { char: '廾', meaning: 'two hands', meaningTR: 'iki el', image: 'minimages/two.png', strokes: 3, reading: 'nijūashi' },
    { char: '弋', meaning: 'shoot', meaningTR: 'atış', image: 'minimages/shoot.png', strokes: 3, reading: 'shikigamae' },
    { char: '弓', meaning: 'bow', meaningTR: 'yay', image: 'minimages/bow.png', strokes: 3, reading: 'yumi' },
    { char: '彐', meaning: 'snout', meaningTR: 'burun', image: 'minimages/snout.png', strokes: 3, reading: 'keigashira' },
    { char: '彡', meaning: 'bristle', meaningTR: 'kıl', image: 'minimages/bristle.png', strokes: 3, reading: 'sanzukuri' },
    { char: '彳', meaning: 'step', meaningTR: 'adım', image: 'minimages/step.png', strokes: 3, reading: 'gyōninben' },

    // 4 strokes
    { char: '心', meaning: 'heart', meaningTR: 'kalp', image: 'minimages/heart.png', strokes: 4, reading: 'kokoro' },
    { char: '戈', meaning: 'halberd', meaningTR: 'mızrak', image: 'minimages/halberd.png', strokes: 4, reading: 'hoko' },
    { char: '戸', meaning: 'door', meaningTR: 'kapı', image: 'minimages/door.png', strokes: 4, reading: 'to' },
    { char: '手', meaning: 'hand', meaningTR: 'el', image: 'minimages/hand.png', strokes: 4, reading: 'te' },
    { char: '支', meaning: 'branch', meaningTR: 'dal', image: 'minimages/branch.png', strokes: 4, reading: 'shinyō' },
    { char: '攴', meaning: 'strike', meaningTR: 'vurmak', image: 'minimages/strike.png', strokes: 4, reading: 'bokunyō' },
    { char: '文', meaning: 'script', meaningTR: 'yazı', image: 'minimages/script.png', strokes: 4, reading: 'bun' },
    { char: '斗', meaning: 'dipper', meaningTR: 'ölçek, kepçe', image: 'minimages/dipper.png', strokes: 4, reading: 'to' },
    { char: '斤', meaning: 'axe', meaningTR: 'balta', image: 'minimages/axe.png', strokes: 4, reading: 'ono' },
    { char: '方', meaning: 'direction, square', meaningTR: 'yön, kare', image: 'minimages/direction.png', strokes: 4, reading: 'hō' },
    { char: '无', meaning: 'not', meaningTR: 'değil', image: 'minimages/not.png', strokes: 4, reading: 'munyō' },
    { char: '日', meaning: 'sun, day', meaningTR: 'güneş, gün', image: 'minimages/sun.png', strokes: 4, reading: 'hi' },
    { char: '曰', meaning: 'say', meaningTR: 'söylemek', image: 'minimages/say.png', strokes: 4, reading: 'iwaku' },
    { char: '月', meaning: 'moon, month', meaningTR: 'ay', image: 'minimages/moon.png', strokes: 4, reading: 'tsuki' },
    { char: '木', meaning: 'tree', meaningTR: 'ağaç', image: 'minimages/tree.png', strokes: 4, reading: 'ki' },
    { char: '欠', meaning: 'lack, yawn', meaningTR: 'eksiklik, esneme', image: 'minimages/lack.png', strokes: 4, reading: 'akubi' },
    { char: '止', meaning: 'stop', meaningTR: 'durmak', image: 'minimages/stop.png', strokes: 4, reading: 'tomeru' },
    { char: '歹', meaning: 'death, decay', meaningTR: 'ölüm, çürüme', image: 'minimages/death.png', strokes: 4, reading: 'gatare' },
    { char: '殳', meaning: 'weapon, lance shaft', meaningTR: 'silah, mızrak sapı', image: 'minimages/weapon.png', strokes: 4, reading: 'rumata' },
    { char: '毋', meaning: 'do not', meaningTR: 'yapma', image: 'minimages/do.png', strokes: 4, reading: 'nakare' },
    { char: '比', meaning: 'compare', meaningTR: 'karşılaştırmak', image: 'minimages/compare.png', strokes: 4, reading: 'kuraberu' },
    { char: '毛', meaning: 'fur, hair', meaningTR: 'kıl, kürk', image: 'minimages/fur.png', strokes: 4, reading: 'ke' },
    { char: '氏', meaning: 'clan, family name', meaningTR: 'klan, soyadı', image: 'minimages/clan.png', strokes: 4, reading: 'uji' },
    { char: '气', meaning: 'steam, air', meaningTR: 'buhar, hava', image: 'minimages/steam.png', strokes: 4, reading: 'kigamae' },
    { char: '水', meaning: 'water', meaningTR: 'su', image: 'minimages/water.png', strokes: 4, reading: 'mizu' },
    { char: '火', meaning: 'fire', meaningTR: 'ateş', image: 'minimages/fire.png', strokes: 4, reading: 'hi' },
    { char: '爪', meaning: 'claw', meaningTR: 'pençe', image: 'minimages/claw.png', strokes: 4, reading: 'tsume' },
    { char: '父', meaning: 'father', meaningTR: 'baba', image: 'minimages/father.png', strokes: 4, reading: 'chichi' },
    { char: '爻', meaning: 'mix, double X', meaningTR: 'karıştırmak', image: 'minimages/mix.png', strokes: 4, reading: 'kō' },
    { char: '爿', meaning: 'split wood', meaningTR: 'yarık odun', image: 'minimages/split.png', strokes: 4, reading: 'shōhen' },
    { char: '片', meaning: 'slice', meaningTR: 'dilim', image: 'minimages/slice.png', strokes: 4, reading: 'kata' },
    { char: '牙', meaning: 'fang', meaningTR: 'diş', image: 'minimages/fang.png', strokes: 4, reading: 'kiba' },
    { char: '牛', meaning: 'cow', meaningTR: 'inek', image: 'minimages/cow.png', strokes: 4, reading: 'ushi' },
    { char: '犬', meaning: 'dog', meaningTR: 'köpek', image: 'minimages/dog.png', strokes: 4, reading: 'inu' },

    // 5 strokes
    { char: '玄', meaning: 'dark', meaningTR: 'karanlık', image: 'minimages/dark.png', strokes: 5, reading: 'gen' },
    { char: '玉', meaning: 'jewel', meaningTR: 'mücevher', image: 'minimages/jewel.png', strokes: 5, reading: 'tama' },
    { char: '瓜', meaning: 'melon', meaningTR: 'karpuz / kavun', image: 'minimages/melon.png', strokes: 5, reading: 'uri' },
    { char: '瓦', meaning: 'tile', meaningTR: 'kiremit', image: 'minimages/tile.png', strokes: 5, reading: 'kawara' },
    { char: '甘', meaning: 'sweet', meaningTR: 'tatlı', image: 'minimages/sweet.png', strokes: 5, reading: 'ama' },
    { char: '生', meaning: 'life, birth', meaningTR: 'yaşam, doğmak', image: 'minimages/life.png', strokes: 5, reading: 'u(mareru)' },
    { char: '用', meaning: 'use', meaningTR: 'kullanmak', image: 'minimages/use.png', strokes: 5, reading: 'mochiiru' },
    { char: '田', meaning: 'rice field', meaningTR: 'pirinç tarlası', image: 'minimages/rice.png', strokes: 5, reading: 'ta' },
    { char: '疋', meaning: 'bolt of cloth, foot', meaningTR: 'top bez, ayak', image: 'minimages/bolt.png', strokes: 5, reading: 'hiki' },
    { char: '疒', meaning: 'sickness', meaningTR: 'hastalık', image: 'minimages/sickness.png', strokes: 5, reading: 'yamai' },
    { char: '癶', meaning: 'footsteps', meaningTR: 'ayak izi', image: 'minimages/footsteps.png', strokes: 5, reading: 'hatsugashira' },
    { char: '白', meaning: 'white', meaningTR: 'beyaz', image: 'minimages/white.png', strokes: 5, reading: 'shiro' },
    { char: '皮', meaning: 'skin', meaningTR: 'deri', image: 'minimages/skin.png', strokes: 5, reading: 'kegawa' },
    { char: '皿', meaning: 'dish', meaningTR: 'tabak', image: 'minimages/dish.png', strokes: 5, reading: 'sara' },
    { char: '目', meaning: 'eye', meaningTR: 'göz', image: 'minimages/eye.png', strokes: 5, reading: 'me' },
    { char: '矛', meaning: 'halberd', meaningTR: 'mızrak', image: 'minimages/halberd.png', strokes: 5, reading: 'hoko' },
    { char: '矢', meaning: 'arrow', meaningTR: 'ok', image: 'minimages/arrow.png', strokes: 5, reading: 'ya' },
    { char: '石', meaning: 'stone', meaningTR: 'taş', image: 'minimages/stone.png', strokes: 5, reading: 'ishi' },
    { char: '示', meaning: 'altar, show', meaningTR: 'sunak, göstermek', image: 'minimages/altar.png', strokes: 5, reading: 'shimesu' },
    { char: '禸', meaning: 'track', meaningTR: 'iz', image: 'minimages/track.png', strokes: 5, reading: 'juunoashi' },
    { char: '禾', meaning: 'grain', meaningTR: 'tahil', image: 'minimages/grain.png', strokes: 5, reading: 'nōge' },
    { char: '穴', meaning: 'hole', meaningTR: 'delik', image: 'minimages/hole.png', strokes: 5, reading: 'ana' },
    { char: '立', meaning: 'stand', meaningTR: 'ayakta durmak', image: 'minimages/stand.png', strokes: 5, reading: 'tatsu' },

    // 6 strokes
    { char: '竹', meaning: 'bamboo', meaningTR: 'bambu', image: 'minimages/bamboo.png', strokes: 6, reading: 'take' },
    { char: '米', meaning: 'rice', meaningTR: 'pirinç', image: 'minimages/rice.png', strokes: 6, reading: 'kome' },
    { char: '糸', meaning: 'thread', meaningTR: 'ip', image: 'minimages/thread.png', strokes: 6, reading: 'ito' },
    { char: '缶', meaning: 'jar', meaningTR: 'kavanoz', image: 'minimages/jar.png', strokes: 6, reading: 'kan' },
    { char: '网', meaning: 'net', meaningTR: 'ağ', image: 'minimages/net.png', strokes: 6, reading: 'ami' },
    { char: '羊', meaning: 'sheep', meaningTR: 'koyun', image: 'minimages/sheep.png', strokes: 6, reading: 'hitsuji' },
    { char: '羽', meaning: 'feather', meaningTR: 'tüy, kanat', image: 'minimages/feather.png', strokes: 6, reading: 'hane' },
    { char: '老', meaning: 'old', meaningTR: 'yaşlı', image: 'minimages/old.png', strokes: 6, reading: 'oi' },
    { char: '而', meaning: 'and then', meaningTR: 've, sonra', image: 'minimages/and.png', strokes: 6, reading: 'shikōshite' },
    { char: '耒', meaning: 'plow', meaningTR: 'saban', image: 'minimages/plow.png', strokes: 6, reading: 'raisuki' },
    { char: '耳', meaning: 'ear', meaningTR: 'kulak', image: 'minimages/ear.png', strokes: 6, reading: 'mimi' },
    { char: '聿', meaning: 'brush', meaningTR: 'fırça', image: 'minimages/brush.png', strokes: 6, reading: 'fude' },
    { char: '肉', meaning: 'meat', meaningTR: 'et', image: 'minimages/meat.png', strokes: 6, reading: 'niku' },
    { char: '臣', meaning: 'minister', meaningTR: 'bakan, hizmetkâr', image: 'minimages/minister.png', strokes: 6, reading: 'shin' },
    { char: '自', meaning: 'self', meaningTR: 'kendisi', image: 'minimages/self.png', strokes: 6, reading: 'mizukara' },
    { char: '至', meaning: 'arrive', meaningTR: 'varmak', image: 'minimages/arrive.png', strokes: 6, reading: 'itaru' },
    { char: '臼', meaning: 'mortar', meaningTR: 'havan', image: 'minimages/mortar.png', strokes: 6, reading: 'usu' },
    { char: '舌', meaning: 'tongue', meaningTR: 'dil', image: 'minimages/tongue.png', strokes: 6, reading: 'shita' },
    { char: '舛', meaning: 'oppose', meaningTR: 'zıt olmak', image: 'minimages/oppose.png', strokes: 6, reading: 'masu' },
    { char: '舟', meaning: 'boat', meaningTR: 'tekne', image: 'minimages/boat.png', strokes: 6, reading: 'fune' },
    { char: '艮', meaning: 'stopping', meaningTR: 'durmak', image: 'minimages/stopping.png', strokes: 6, reading: 'kon' },
    { char: '色', meaning: 'color', meaningTR: 'renk', image: 'minimages/color.png', strokes: 6, reading: 'iro' },
    { char: '艸', meaning: 'grass', meaningTR: 'ot', image: 'minimages/grass.png', strokes: 6, reading: 'kusa' },
    { char: '虍', meaning: 'tiger', meaningTR: 'kaplan işareti', image: 'minimages/tiger.png', strokes: 6, reading: 'tora' },
    { char: '虫', meaning: 'insect', meaningTR: 'böcek', image: 'minimages/insect.png', strokes: 6, reading: 'mushi' },
    { char: '血', meaning: 'blood', meaningTR: 'kan', image: 'minimages/blood.png', strokes: 6, reading: 'chi' },
    { char: '行', meaning: 'go, do', meaningTR: 'gitmek, yapmak', image: 'minimages/go.png', strokes: 6, reading: 'gyō' },
    { char: '衣', meaning: 'clothes', meaningTR: 'giysi', image: 'minimages/clothes.png', strokes: 6, reading: 'koromo' },
    { char: '襾', meaning: 'cover, west', meaningTR: 'örtü, batı', image: 'minimages/cover.png', strokes: 6, reading: 'nishi' },

    // 7 strokes
    { char: '見', meaning: 'see', meaningTR: 'görmek', image: 'minimages/see.png', strokes: 7, reading: 'miru' },
    { char: '角', meaning: 'horn', meaningTR: 'boynuz', image: 'minimages/horn.png', strokes: 7, reading: 'tsuno' },
    { char: '言', meaning: 'speech', meaningTR: 'söz', image: 'minimages/speech.png', strokes: 7, reading: 'gen' },
    { char: '谷', meaning: 'valley', meaningTR: 'vadi', image: 'minimages/valley.png', strokes: 7, reading: 'tani' },
    { char: '豆', meaning: 'bean', meaningTR: 'fasulye', image: 'minimages/bean.png', strokes: 7, reading: 'mame' },
    { char: '豕', meaning: 'pig', meaningTR: 'domuz', image: 'minimages/pig.png', strokes: 7, reading: 'inoshishi' },
    { char: '豸', meaning: 'badger, beast', meaningTR: 'porsuk, yaratık', image: 'minimages/badger.png', strokes: 7, reading: 'mujina' },
    { char: '貝', meaning: 'shell, money', meaningTR: 'kabuk, para', image: 'minimages/shell.png', strokes: 7, reading: 'kai' },
    { char: '赤', meaning: 'red', meaningTR: 'kırmızı', image: 'minimages/red.png', strokes: 7, reading: 'aka' },
    { char: '走', meaning: 'run', meaningTR: 'koşmak', image: 'minimages/run.png', strokes: 7, reading: 'hashiru' },
    { char: '足', meaning: 'foot', meaningTR: 'ayak', image: 'minimages/foot.png', strokes: 7, reading: 'ashi' },
    { char: '身', meaning: 'body', meaningTR: 'vücut', image: 'minimages/body.png', strokes: 7, reading: 'mi' },
    { char: '車', meaning: 'cart, car', meaningTR: 'araba', image: 'minimages/cart.png', strokes: 7, reading: 'kuruma' },
    { char: '辛', meaning: 'bitter', meaningTR: 'acı', image: 'minimages/bitter.png', strokes: 7, reading: 'karai' },
    { char: '辰', meaning: 'dragon sign', meaningTR: 'ejderha burcu', image: 'minimages/dragon.png', strokes: 7, reading: 'shinnotatsu' },
    { char: '辵', meaning: 'walk', meaningTR: 'yürümek', image: 'minimages/walk.png', strokes: 7, reading: 'shinnyō' },
    { char: '邑', meaning: 'village', meaningTR: 'köy', image: 'minimages/village.png', strokes: 7, reading: 'mura' },
    { char: '酉', meaning: 'wine, bird sign', meaningTR: 'şarap, horoz burcu', image: 'minimages/wine.png', strokes: 7, reading: 'tori' },
    { char: '釆', meaning: 'distinguish', meaningTR: 'ayırt etmek', image: 'minimages/distinguish.png', strokes: 7, reading: 'nogome' },
    { char: '里', meaning: 'village, unit', meaningTR: 'köy, mesafe birimi', image: 'minimages/village.png', strokes: 7, reading: 'sato' },

    // 8 strokes
    { char: '金', meaning: 'metal, gold', meaningTR: 'metal, altın', image: 'minimages/metal.png', strokes: 8, reading: 'kane' },
    { char: '長', meaning: 'long, leader', meaningTR: 'uzun, lider', image: 'minimages/long.png', strokes: 8, reading: 'nagai' },
    { char: '門', meaning: 'gate', meaningTR: 'kapı', image: 'minimages/gate.png', strokes: 8, reading: 'mon' },
    { char: '阜', meaning: 'mound', meaningTR: 'tümsek', image: 'minimages/mound.png', strokes: 8, reading: 'oka' },
    { char: '隶', meaning: 'slave', meaningTR: 'köle', image: 'minimages/slave.png', strokes: 8, reading: 'rei' },
    { char: '隹', meaning: 'short-tailed bird', meaningTR: 'kısa kuyruklu kuş', image: 'minimages/short-tailed.png', strokes: 8, reading: 'furutori' },
    { char: '雨', meaning: 'rain', meaningTR: 'yağmur', image: 'minimages/rain.png', strokes: 8, reading: 'ame' },
    { char: '青', meaning: 'blue, green', meaningTR: 'mavi, yeşil', image: 'minimages/blue.png', strokes: 8, reading: 'ao' },
    { char: '非', meaning: 'wrong, not', meaningTR: 'yanlış, değil', image: 'minimages/wrong.png', strokes: 8, reading: 'arazu' },

    // 9 strokes
    { char: '面', meaning: 'face', meaningTR: 'yüz', image: 'minimages/face.png', strokes: 9, reading: 'men' },
    { char: '革', meaning: 'leather', meaningTR: 'deri', image: 'minimages/leather.png', strokes: 9, reading: 'kawa' },
    { char: '韋', meaning: 'tanned leather', meaningTR: 'tabaklanmış deri', image: 'minimages/tanned.png', strokes: 9, reading: 'nimeshi-gawa' },
    { char: '韭', meaning: 'leek', meaningTR: 'pırasa', image: 'minimages/leek.png', strokes: 9, reading: 'nira' },
    { char: '音', meaning: 'sound', meaningTR: 'ses', image: 'minimages/sound.png', strokes: 9, reading: 'oto' },
    { char: '頁', meaning: 'head, page', meaningTR: 'baş, sayfa', image: 'minimages/head.png', strokes: 9, reading: 'ōgai' },
    { char: '風', meaning: 'wind', meaningTR: 'rüzgar', image: 'minimages/wind.png', strokes: 9, reading: 'kaze' },
    { char: '飛', meaning: 'fly', meaningTR: 'uçmak', image: 'minimages/fly.png', strokes: 9, reading: 'tobu' },
    { char: '食', meaning: 'eat, food', meaningTR: 'yemek', image: 'minimages/eat.png', strokes: 9, reading: 'shoku' },
    { char: '首', meaning: 'neck, head', meaningTR: 'boyun, baş', image: 'minimages/neck.png', strokes: 9, reading: 'kubi' },
    { char: '香', meaning: 'fragrance', meaningTR: 'koku', image: 'minimages/fragrance.png', strokes: 9, reading: 'kaori' },

    // 10 strokes
    { char: '馬', meaning: 'horse', meaningTR: 'at', image: 'minimages/horse.png', strokes: 10, reading: 'uma' },
    { char: '骨', meaning: 'bone', meaningTR: 'kemik', image: 'minimages/bone.png', strokes: 10, reading: 'hone' },
    { char: '高', meaning: 'tall, high', meaningTR: 'yüksek', image: 'minimages/tall.png', strokes: 10, reading: 'taka(i)' },
    { char: '髟', meaning: 'hair', meaningTR: 'saç', image: 'minimages/hair.png', strokes: 10, reading: 'kamigashira' },
    { char: '鬥', meaning: 'fight', meaningTR: 'dövüş', image: 'minimages/fight.png', strokes: 10, reading: 'tatakaigamae' },
    { char: '鬯', meaning: 'sacrificial wine', meaningTR: 'kurban şarabı', image: 'minimages/sacrificial.png', strokes: 10, reading: 'nioraizake' },
    { char: '鬲', meaning: 'tripod', meaningTR: 'üç ayaklı kap', image: 'minimages/tripod.png', strokes: 10, reading: 'kanae' },
    { char: '鬼', meaning: 'ghost, demon', meaningTR: 'iblis, hayalet', image: 'minimages/ghost.png', strokes: 10, reading: 'oni' },

    // 11 strokes
    { char: '魚', meaning: 'fish', meaningTR: 'balık', image: 'minimages/fish.png', strokes: 11, reading: 'uo' },
    { char: '鳥', meaning: 'bird', meaningTR: 'kuş', image: 'minimages/bird.png', strokes: 11, reading: 'tori' },
    { char: '鹵', meaning: 'salt', meaningTR: 'tuz', image: 'minimages/salt.png', strokes: 11, reading: 'shio' },
    { char: '鹿', meaning: 'deer', meaningTR: 'geyik', image: 'minimages/deer.png', strokes: 11, reading: 'shika' },
    { char: '麥', meaning: 'wheat', meaningTR: 'buğday', image: 'minimages/wheat.png', strokes: 11, reading: 'mugi' },
    { char: '麻', meaning: 'hemp', meaningTR: 'kenevir', image: 'minimages/hemp.png', strokes: 11, reading: 'asa' },

    // 12 strokes
    { char: '黃', meaning: 'yellow', meaningTR: 'sarı', image: 'minimages/yellow.png', strokes: 12, reading: 'ki' },
    { char: '黍', meaning: 'millet', meaningTR: 'darı', image: 'minimages/millet.png', strokes: 12, reading: 'kibi' },
    { char: '黑', meaning: 'black', meaningTR: 'siyah', image: 'minimages/black.png', strokes: 12, reading: 'kuro' },
    { char: '黹', meaning: 'embroidery', meaningTR: 'nakış', image: 'minimages/embroidery.png', strokes: 12, reading: 'nuitori' },

    // 13 strokes
    { char: '黽', meaning: 'frog', meaningTR: 'kurbağa', image: 'minimages/frog.png', strokes: 13, reading: 'kaeru' },
    { char: '鼎', meaning: 'tripod', meaningTR: 'üç ayaklı kazan', image: 'minimages/tripod.png', strokes: 13, reading: 'kanae' },
    { char: '鼓', meaning: 'drum', meaningTR: 'davul', image: 'minimages/drum.png', strokes: 13, reading: 'tsudzumi' },
    { char: '鼠', meaning: 'rat, mouse', meaningTR: 'sıçan', image: 'minimages/rat.png', strokes: 13, reading: 'nezumi' },

    // 14 strokes
    { char: '鼻', meaning: 'nose', meaningTR: 'burun', image: 'minimages/nose.png', strokes: 14, reading: 'hana' },
    { char: '齊', meaning: 'alike, equal', meaningTR: 'eşit, aynı', image: 'minimages/alike.png', strokes: 14, reading: 'sei' },

    // 15 strokes
    { char: '齒', meaning: 'tooth', meaningTR: 'diş', image: 'minimages/tooth.png', strokes: 15, reading: 'ha' },

    // 16 strokes
    { char: '龍', meaning: 'dragon', meaningTR: 'ejderha', image: 'minimages/dragon.png', strokes: 16, reading: 'ryū' },
    { char: '龜', meaning: 'turtle', meaningTR: 'kaplumbağa', image: 'minimages/turtle.png', strokes: 16, reading: 'kame' },

    // 17 strokes
    { char: '龠', meaning: 'flute', meaningTR: 'flüt', image: 'minimages/flute.png', strokes: 17, reading: 'yaku' }
];
