const radicals = [
    // 1 stroke
    { char: '一', meaning: 'one', meaningTR: 'bir', strokes: 1, reading: 'ichi' },
    { char: '丨', meaning: 'line', meaningTR: 'çizgi', strokes: 1, reading: 'bō' },
    { char: '丶', meaning: 'dot', meaningTR: 'nokta', strokes: 1, reading: 'ten' },
    { char: '丿', meaning: 'slash', meaningTR: 'eğik çizgi', strokes: 1, reading: 'no' },
    { char: '乙', meaning: 'second', meaningTR: 'ikinci', strokes: 1, reading: 'otsu' },
    { char: '亅', meaning: 'hook', meaningTR: 'kanca', strokes: 1, reading: 'hane' },

    // 2 strokes
    { char: '二', meaning: 'two', meaningTR: 'iki', strokes: 2, reading: 'ni' },
    { char: '亠', meaning: 'lid', meaningTR: 'kapak', strokes: 2, reading: 'nabebuta' },
    { char: '人', meaning: 'person', meaningTR: 'insan', strokes: 2, reading: 'hito' },
    { char: '儿', meaning: 'legs', meaningTR: 'bacaklar', strokes: 2, reading: 'hitoashi' },
    { char: '入', meaning: 'enter', meaningTR: 'girmek', strokes: 2, reading: 'iru' },
    { char: '八', meaning: 'eight', meaningTR: 'sekiz', strokes: 2, reading: 'hachi' },
    { char: '冂', meaning: 'down box', meaningTR: 'açık kutu', strokes: 2, reading: 'keigamae' },
    { char: '冖', meaning: 'cover', meaningTR: 'örtü', strokes: 2, reading: 'ukanmuri' },
    { char: '冫', meaning: 'ice', meaningTR: 'buz', strokes: 2, reading: 'nisui' },
    { char: '几', meaning: 'table', meaningTR: 'masa', strokes: 2, reading: 'kinyou' },
    { char: '凵', meaning: 'container', meaningTR: 'kap', strokes: 2, reading: 'kannyou' },
    { char: '刀', meaning: 'knife, sword', meaningTR: 'bıçak, kılıç', strokes: 2, reading: 'katana' },
    { char: '力', meaning: 'power', meaningTR: 'güç', strokes: 2, reading: 'chikara' },
    { char: '勹', meaning: 'wrap', meaningTR: 'sarmak', strokes: 2, reading: 'tsutsumigamae' },
    { char: '匕', meaning: 'spoon', meaningTR: 'kaşık', strokes: 2, reading: 'saji' },
    { char: '匚', meaning: 'box', meaningTR: 'kutu', strokes: 2, reading: 'hakogamae' },
    { char: '匸', meaning: 'hide', meaningTR: 'gizleme', strokes: 2, reading: 'kakushigamae' },
    { char: '十', meaning: 'ten', meaningTR: 'on', strokes: 2, reading: 'jū' },
    { char: '卜', meaning: 'divination', meaningTR: 'kehanet', strokes: 2, reading: 'boku' },
    { char: '卩', meaning: 'seal', meaningTR: 'mühür', strokes: 2, reading: 'fushizukuri' },
    { char: '厂', meaning: 'cliff', meaningTR: 'uçurum', strokes: 2, reading: 'gandare' },
    { char: '厶', meaning: 'private', meaningTR: 'özel', strokes: 2, reading: 'mu' },
    { char: '又', meaning: 'again', meaningTR: 'tekrar', strokes: 2, reading: 'mata' },

    // 3 strokes
    { char: '口', meaning: 'mouth', meaningTR: 'ağız', strokes: 3, reading: 'kuchi' },
    { char: '囗', meaning: 'enclosure', meaningTR: 'çevreleme', strokes: 3, reading: 'kunigamae' },
    { char: '土', meaning: 'earth', meaningTR: 'toprak', strokes: 3, reading: 'tsuchi' },
    { char: '士', meaning: 'scholar, samurai', meaningTR: 'bilgin, samuray', strokes: 3, reading: 'shi' },
    { char: '夂', meaning: 'go slowly', meaningTR: 'yavaş gitmek', strokes: 3, reading: 'sui' },
    { char: '夊', meaning: 'go slowly (variant)', meaningTR: 'yavaş gitmek (varyant)', strokes: 3, reading: 'suinyō' },
    { char: '夕', meaning: 'evening', meaningTR: 'akşam', strokes: 3, reading: 'yū' },
    { char: '大', meaning: 'big', meaningTR: 'büyük', strokes: 3, reading: 'dai' },
    { char: '女', meaning: 'woman', meaningTR: 'kadın', strokes: 3, reading: 'onna' },
    { char: '子', meaning: 'child', meaningTR: 'çocuk', strokes: 3, reading: 'ko' },
    { char: '宀', meaning: 'roof', meaningTR: 'çatı', strokes: 3, reading: 'ukanmuri' },
    { char: '寸', meaning: 'inch', meaningTR: 'inç', strokes: 3, reading: 'sun' },
    { char: '小', meaning: 'small', meaningTR: 'küçük', strokes: 3, reading: 'shō' },
    { char: '尢', meaning: 'lame', meaningTR: 'topal', strokes: 3, reading: 'dainomageashi' },
    { char: '尸', meaning: 'corpse', meaningTR: 'ceset', strokes: 3, reading: 'shikabane' },
    { char: '屮', meaning: 'sprout', meaningTR: 'filiz', strokes: 3, reading: 'tetsu' },
    { char: '山', meaning: 'mountain', meaningTR: 'dağ', strokes: 3, reading: 'yama' },
    { char: '川', meaning: 'river', meaningTR: 'nehir', strokes: 3, reading: 'kawa' },
    { char: '工', meaning: 'work', meaningTR: 'iş', strokes: 3, reading: 'takumi' },
    { char: '己', meaning: 'self', meaningTR: 'kendi', strokes: 3, reading: 'onore' },
    { char: '巾', meaning: 'cloth', meaningTR: 'bez', strokes: 3, reading: 'haba' },
    { char: '干', meaning: 'dry', meaningTR: 'kuru', strokes: 3, reading: 'kan' },
    { char: '幺', meaning: 'short thread', meaningTR: 'kısa iplik', strokes: 3, reading: 'yō' },
    { char: '广', meaning: 'shelter', meaningTR: 'çatı, sığınak', strokes: 3, reading: 'madare' },
    { char: '廴', meaning: 'long stride', meaningTR: 'uzun adım', strokes: 3, reading: 'ennyō' },
    { char: '廾', meaning: 'two hands', meaningTR: 'iki el', strokes: 3, reading: 'nijūashi' },
    { char: '弋', meaning: 'shoot', meaningTR: 'atış', strokes: 3, reading: 'shikigamae' },
    { char: '弓', meaning: 'bow', meaningTR: 'yay', strokes: 3, reading: 'yumi' },
    { char: '彐', meaning: 'snout', meaningTR: 'burun', strokes: 3, reading: 'keigashira' },
    { char: '彡', meaning: 'bristle', meaningTR: 'kıl', strokes: 3, reading: 'sanzukuri' },
    { char: '彳', meaning: 'step', meaningTR: 'adım', strokes: 3, reading: 'gyōninben' },

    // 4 strokes
    { char: '心', meaning: 'heart', meaningTR: 'kalp', strokes: 4, reading: 'kokoro' },
    { char: '戈', meaning: 'halberd', meaningTR: 'mızrak', strokes: 4, reading: 'hoko' },
    { char: '戸', meaning: 'door', meaningTR: 'kapı', strokes: 4, reading: 'to' },
    { char: '手', meaning: 'hand', meaningTR: 'el', strokes: 4, reading: 'te' },
    { char: '支', meaning: 'branch', meaningTR: 'dal', strokes: 4, reading: 'shinyō' },
    { char: '攴', meaning: 'strike', meaningTR: 'vurmak', strokes: 4, reading: 'bokunyō' },
    { char: '文', meaning: 'script', meaningTR: 'yazı', strokes: 4, reading: 'bun' },
    { char: '斗', meaning: 'dipper', meaningTR: 'ölçek, kepçe', strokes: 4, reading: 'to' },
    { char: '斤', meaning: 'axe', meaningTR: 'balta', strokes: 4, reading: 'ono' },
    { char: '方', meaning: 'direction, square', meaningTR: 'yön, kare', strokes: 4, reading: 'hō' },
    { char: '无', meaning: 'not', meaningTR: 'değil', strokes: 4, reading: 'munyō' },
    { char: '日', meaning: 'sun, day', meaningTR: 'güneş, gün', strokes: 4, reading: 'hi' },
    { char: '曰', meaning: 'say', meaningTR: 'söylemek', strokes: 4, reading: 'iwaku' },
    { char: '月', meaning: 'moon, month', meaningTR: 'ay', strokes: 4, reading: 'tsuki' },
    { char: '木', meaning: 'tree', meaningTR: 'ağaç', strokes: 4, reading: 'ki' },
    { char: '欠', meaning: 'lack, yawn', meaningTR: 'eksiklik, esneme', strokes: 4, reading: 'akubi' },
    { char: '止', meaning: 'stop', meaningTR: 'durmak', strokes: 4, reading: 'tomeru' },
    { char: '歹', meaning: 'death, decay', meaningTR: 'ölüm, çürüme', strokes: 4, reading: 'gatare' },
    { char: '殳', meaning: 'weapon, lance shaft', meaningTR: 'silah, mızrak sapı', strokes: 4, reading: 'rumata' },
    { char: '毋', meaning: 'do not', meaningTR: 'yapma', strokes: 4, reading: 'nakare' },
    { char: '比', meaning: 'compare', meaningTR: 'karşılaştırmak', strokes: 4, reading: 'kuraberu' },
    { char: '毛', meaning: 'fur, hair', meaningTR: 'kıl, kürk', strokes: 4, reading: 'ke' },
    { char: '氏', meaning: 'clan, family name', meaningTR: 'klan, soyadı', strokes: 4, reading: 'uji' },
    { char: '气', meaning: 'steam, air', meaningTR: 'buhar, hava', strokes: 4, reading: 'kigamae' },
    { char: '水', meaning: 'water', meaningTR: 'su', strokes: 4, reading: 'mizu' },
    { char: '火', meaning: 'fire', meaningTR: 'ateş', strokes: 4, reading: 'hi' },
    { char: '爪', meaning: 'claw', meaningTR: 'pençe', strokes: 4, reading: 'tsume' },
    { char: '父', meaning: 'father', meaningTR: 'baba', strokes: 4, reading: 'chichi' },
    { char: '爻', meaning: 'mix, double X', meaningTR: 'karıştırmak', strokes: 4, reading: 'kō' },
    { char: '爿', meaning: 'split wood', meaningTR: 'yarık odun', strokes: 4, reading: 'shōhen' },
    { char: '片', meaning: 'slice', meaningTR: 'dilim', strokes: 4, reading: 'kata' },
    { char: '牙', meaning: 'fang', meaningTR: 'diş', strokes: 4, reading: 'kiba' },
    { char: '牛', meaning: 'cow', meaningTR: 'inek', strokes: 4, reading: 'ushi' },
    { char: '犬', meaning: 'dog', meaningTR: 'köpek', strokes: 4, reading: 'inu' },

    // 5 strokes
    { char: '玄', meaning: 'dark', meaningTR: 'karanlık', strokes: 5, reading: 'gen' },
    { char: '玉', meaning: 'jewel', meaningTR: 'mücevher', strokes: 5, reading: 'tama' },
    { char: '瓜', meaning: 'melon', meaningTR: 'karpuz / kavun', strokes: 5, reading: 'uri' },
    { char: '瓦', meaning: 'tile', meaningTR: 'kiremit', strokes: 5, reading: 'kawara' },
    { char: '甘', meaning: 'sweet', meaningTR: 'tatlı', strokes: 5, reading: 'ama' },
    { char: '生', meaning: 'life, birth', meaningTR: 'yaşam, doğmak', strokes: 5, reading: 'u(mareru)' },
    { char: '用', meaning: 'use', meaningTR: 'kullanmak', strokes: 5, reading: 'mochiiru' },
    { char: '田', meaning: 'rice field', meaningTR: 'pirinç tarlası', strokes: 5, reading: 'ta' },
    { char: '疋', meaning: 'bolt of cloth, foot', meaningTR: 'top bez, ayak', strokes: 5, reading: 'hiki' },
    { char: '疒', meaning: 'sickness', meaningTR: 'hastalık', strokes: 5, reading: 'yamai' },
    { char: '癶', meaning: 'footsteps', meaningTR: 'ayak izi', strokes: 5, reading: 'hatsugashira' },
    { char: '白', meaning: 'white', meaningTR: 'beyaz', strokes: 5, reading: 'shiro' },
    { char: '皮', meaning: 'skin', meaningTR: 'deri', strokes: 5, reading: 'kegawa' },
    { char: '皿', meaning: 'dish', meaningTR: 'tabak', strokes: 5, reading: 'sara' },
    { char: '目', meaning: 'eye', meaningTR: 'göz', strokes: 5, reading: 'me' },
    { char: '矛', meaning: 'halberd', meaningTR: 'mızrak', strokes: 5, reading: 'hoko' },
    { char: '矢', meaning: 'arrow', meaningTR: 'ok', strokes: 5, reading: 'ya' },
    { char: '石', meaning: 'stone', meaningTR: 'taş', strokes: 5, reading: 'ishi' },
    { char: '示', meaning: 'altar, show', meaningTR: 'sunak, göstermek', strokes: 5, reading: 'shimesu' },
    { char: '禸', meaning: 'track', meaningTR: 'iz', strokes: 5, reading: 'juunoashi' },
    { char: '禾', meaning: 'grain', meaningTR: 'tahil', strokes: 5, reading: 'nōge' },
    { char: '穴', meaning: 'hole', meaningTR: 'delik', strokes: 5, reading: 'ana' },
    { char: '立', meaning: 'stand', meaningTR: 'ayakta durmak', strokes: 5, reading: 'tatsu' },

    // 6 strokes
    { char: '竹', meaning: 'bamboo', meaningTR: 'bambu', strokes: 6, reading: 'take' },
    { char: '米', meaning: 'rice', meaningTR: 'pirinç', strokes: 6, reading: 'kome' },
    { char: '糸', meaning: 'thread', meaningTR: 'ip', strokes: 6, reading: 'ito' },
    { char: '缶', meaning: 'jar', meaningTR: 'kavanoz', strokes: 6, reading: 'kan' },
    { char: '网', meaning: 'net', meaningTR: 'ağ', strokes: 6, reading: 'ami' },
    { char: '羊', meaning: 'sheep', meaningTR: 'koyun', strokes: 6, reading: 'hitsuji' },
    { char: '羽', meaning: 'feather', meaningTR: 'tüy, kanat', strokes: 6, reading: 'hane' },
    { char: '老', meaning: 'old', meaningTR: 'yaşlı', strokes: 6, reading: 'oi' },
    { char: '而', meaning: 'and then', meaningTR: 've, sonra', strokes: 6, reading: 'shikōshite' },
    { char: '耒', meaning: 'plow', meaningTR: 'saban', strokes: 6, reading: 'raisuki' },
    { char: '耳', meaning: 'ear', meaningTR: 'kulak', strokes: 6, reading: 'mimi' },
    { char: '聿', meaning: 'brush', meaningTR: 'fırça', strokes: 6, reading: 'fude' },
    { char: '肉', meaning: 'meat', meaningTR: 'et', strokes: 6, reading: 'niku' },
    { char: '臣', meaning: 'minister', meaningTR: 'bakan, hizmetkâr', strokes: 6, reading: 'shin' },
    { char: '自', meaning: 'self', meaningTR: 'kendisi', strokes: 6, reading: 'mizukara' },
    { char: '至', meaning: 'arrive', meaningTR: 'varmak', strokes: 6, reading: 'itaru' },
    { char: '臼', meaning: 'mortar', meaningTR: 'havan', strokes: 6, reading: 'usu' },
    { char: '舌', meaning: 'tongue', meaningTR: 'dil', strokes: 6, reading: 'shita' },
    { char: '舛', meaning: 'oppose', meaningTR: 'zıt olmak', strokes: 6, reading: 'masu' },
    { char: '舟', meaning: 'boat', meaningTR: 'tekne', strokes: 6, reading: 'fune' },
    { char: '艮', meaning: 'stopping', meaningTR: 'durmak', strokes: 6, reading: 'kon' },
    { char: '色', meaning: 'color', meaningTR: 'renk', strokes: 6, reading: 'iro' },
    { char: '艸', meaning: 'grass', meaningTR: 'ot', strokes: 6, reading: 'kusa' },
    { char: '虍', meaning: 'tiger', meaningTR: 'kaplan işareti', strokes: 6, reading: 'tora' },
    { char: '虫', meaning: 'insect', meaningTR: 'böcek', strokes: 6, reading: 'mushi' },
    { char: '血', meaning: 'blood', meaningTR: 'kan', strokes: 6, reading: 'chi' },
    { char: '行', meaning: 'go, do', meaningTR: 'gitmek, yapmak', strokes: 6, reading: 'gyō' },
    { char: '衣', meaning: 'clothes', meaningTR: 'giysi', strokes: 6, reading: 'koromo' },
    { char: '襾', meaning: 'cover, west', meaningTR: 'örtü, batı', strokes: 6, reading: 'nishi' },

    // 7 strokes
    { char: '見', meaning: 'see', meaningTR: 'görmek', strokes: 7, reading: 'miru' },
    { char: '角', meaning: 'horn', meaningTR: 'boynuz', strokes: 7, reading: 'tsuno' },
    { char: '言', meaning: 'speech', meaningTR: 'söz', strokes: 7, reading: 'gen' },
    { char: '谷', meaning: 'valley', meaningTR: 'vadi', strokes: 7, reading: 'tani' },
    { char: '豆', meaning: 'bean', meaningTR: 'fasulye', strokes: 7, reading: 'mame' },
    { char: '豕', meaning: 'pig', meaningTR: 'domuz', strokes: 7, reading: 'inoshishi' },
    { char: '豸', meaning: 'badger, beast', meaningTR: 'porsuk, yaratık', strokes: 7, reading: 'mujina' },
    { char: '貝', meaning: 'shell, money', meaningTR: 'kabuk, para', strokes: 7, reading: 'kai' },
    { char: '赤', meaning: 'red', meaningTR: 'kırmızı', strokes: 7, reading: 'aka' },
    { char: '走', meaning: 'run', meaningTR: 'koşmak', strokes: 7, reading: 'hashiru' },
    { char: '足', meaning: 'foot', meaningTR: 'ayak', strokes: 7, reading: 'ashi' },
    { char: '身', meaning: 'body', meaningTR: 'vücut', strokes: 7, reading: 'mi' },
    { char: '車', meaning: 'cart, car', meaningTR: 'araba', strokes: 7, reading: 'kuruma' },
    { char: '辛', meaning: 'bitter', meaningTR: 'acı', strokes: 7, reading: 'karai' },
    { char: '辰', meaning: 'dragon sign', meaningTR: 'ejderha burcu', strokes: 7, reading: 'shinnotatsu' },
    { char: '辵', meaning: 'walk', meaningTR: 'yürümek', strokes: 7, reading: 'shinnyō' },
    { char: '邑', meaning: 'village', meaningTR: 'köy', strokes: 7, reading: 'mura' },
    { char: '酉', meaning: 'wine, bird sign', meaningTR: 'şarap, horoz burcu', strokes: 7, reading: 'tori' },
    { char: '釆', meaning: 'distinguish', meaningTR: 'ayırt etmek', strokes: 7, reading: 'nogome' },
    { char: '里', meaning: 'village, unit', meaningTR: 'köy, mesafe birimi', strokes: 7, reading: 'sato' },

    // 8 strokes
    { char: '金', meaning: 'metal, gold', meaningTR: 'metal, altın', strokes: 8, reading: 'kane' },
    { char: '長', meaning: 'long, leader', meaningTR: 'uzun, lider', strokes: 8, reading: 'nagai' },
    { char: '門', meaning: 'gate', meaningTR: 'kapı', strokes: 8, reading: 'mon' },
    { char: '阜', meaning: 'mound', meaningTR: 'tümsek', strokes: 8, reading: 'oka' },
    { char: '隶', meaning: 'slave', meaningTR: 'köle', strokes: 8, reading: 'rei' },
    { char: '隹', meaning: 'short-tailed bird', meaningTR: 'kısa kuyruklu kuş', strokes: 8, reading: 'furutori' },
    { char: '雨', meaning: 'rain', meaningTR: 'yağmur', strokes: 8, reading: 'ame' },
    { char: '青', meaning: 'blue, green', meaningTR: 'mavi, yeşil', strokes: 8, reading: 'ao' },
    { char: '非', meaning: 'wrong, not', meaningTR: 'yanlış, değil', strokes: 8, reading: 'arazu' },

    // 9 strokes
    { char: '面', meaning: 'face', meaningTR: 'yüz', strokes: 9, reading: 'men' },
    { char: '革', meaning: 'leather', meaningTR: 'deri', strokes: 9, reading: 'kawa' },
    { char: '韋', meaning: 'tanned leather', meaningTR: 'tabaklanmış deri', strokes: 9, reading: 'nimeshi-gawa' },
    { char: '韭', meaning: 'leek', meaningTR: 'pırasa', strokes: 9, reading: 'nira' },
    { char: '音', meaning: 'sound', meaningTR: 'ses', strokes: 9, reading: 'oto' },
    { char: '頁', meaning: 'head, page', meaningTR: 'baş, sayfa', strokes: 9, reading: 'ōgai' },
    { char: '風', meaning: 'wind', meaningTR: 'rüzgar', strokes: 9, reading: 'kaze' },
    { char: '飛', meaning: 'fly', meaningTR: 'uçmak', strokes: 9, reading: 'tobu' },
    { char: '食', meaning: 'eat, food', meaningTR: 'yemek', strokes: 9, reading: 'shoku' },
    { char: '首', meaning: 'neck, head', meaningTR: 'boyun, baş', strokes: 9, reading: 'kubi' },
    { char: '香', meaning: 'fragrance', meaningTR: 'koku', strokes: 9, reading: 'kaori' },

    // 10 strokes
    { char: '馬', meaning: 'horse', meaningTR: 'at', strokes: 10, reading: 'uma' },
    { char: '骨', meaning: 'bone', meaningTR: 'kemik', strokes: 10, reading: 'hone' },
    { char: '高', meaning: 'tall, high', meaningTR: 'yüksek', strokes: 10, reading: 'taka(i)' },
    { char: '髟', meaning: 'hair', meaningTR: 'saç', strokes: 10, reading: 'kamigashira' },
    { char: '鬥', meaning: 'fight', meaningTR: 'dövüş', strokes: 10, reading: 'tatakaigamae' },
    { char: '鬯', meaning: 'sacrificial wine', meaningTR: 'kurban şarabı', strokes: 10, reading: 'nioraizake' },
    { char: '鬲', meaning: 'tripod', meaningTR: 'üç ayaklı kap', strokes: 10, reading: 'kanae' },
    { char: '鬼', meaning: 'ghost, demon', meaningTR: 'iblis, hayalet', strokes: 10, reading: 'oni' },

    // 11 strokes
    { char: '魚', meaning: 'fish', meaningTR: 'balık', strokes: 11, reading: 'uo' },
    { char: '鳥', meaning: 'bird', meaningTR: 'kuş', strokes: 11, reading: 'tori' },
    { char: '鹵', meaning: 'salt', meaningTR: 'tuz', strokes: 11, reading: 'shio' },
    { char: '鹿', meaning: 'deer', meaningTR: 'geyik', strokes: 11, reading: 'shika' },
    { char: '麥', meaning: 'wheat', meaningTR: 'buğday', strokes: 11, reading: 'mugi' },
    { char: '麻', meaning: 'hemp', meaningTR: 'kenevir', strokes: 11, reading: 'asa' },

    // 12 strokes
    { char: '黃', meaning: 'yellow', meaningTR: 'sarı', strokes: 12, reading: 'ki' },
    { char: '黍', meaning: 'millet', meaningTR: 'darı', strokes: 12, reading: 'kibi' },
    { char: '黑', meaning: 'black', meaningTR: 'siyah', strokes: 12, reading: 'kuro' },
    { char: '黹', meaning: 'embroidery', meaningTR: 'nakış', strokes: 12, reading: 'nuitori' },

    // 13 strokes
    { char: '黽', meaning: 'frog', meaningTR: 'kurbağa', strokes: 13, reading: 'kaeru' },
    { char: '鼎', meaning: 'tripod', meaningTR: 'üç ayaklı kazan', strokes: 13, reading: 'kanae' },
    { char: '鼓', meaning: 'drum', meaningTR: 'davul', strokes: 13, reading: 'tsudzumi' },
    { char: '鼠', meaning: 'rat, mouse', meaningTR: 'sıçan', strokes: 13, reading: 'nezumi' },

    // 14 strokes
    { char: '鼻', meaning: 'nose', meaningTR: 'burun', strokes: 14, reading: 'hana' },
    { char: '齊', meaning: 'alike, equal', meaningTR: 'eşit, aynı', strokes: 14, reading: 'sei' },

    // 15 strokes
    { char: '齒', meaning: 'tooth', meaningTR: 'diş', strokes: 15, reading: 'ha' },

    // 16 strokes
    { char: '龍', meaning: 'dragon', meaningTR: 'ejderha', strokes: 16, reading: 'ryū' },
    { char: '龜', meaning: 'turtle', meaningTR: 'kaplumbağa', strokes: 16, reading: 'kame' },

    // 17 strokes
    { char: '龠', meaning: 'flute', meaningTR: 'flüt', strokes: 17, reading: 'yaku' }
];
