import assert from "node:assert/strict";
import { access, readFile } from "node:fs/promises";
import test from "node:test";

test("GitHub Pages paketi doğru domain ve varlıklarla hazırdır", async () => {
  const html = await readFile(new URL("../.pages-build/index.html", import.meta.url), "utf8");
  assert.match(html, /<title>REDBALL/i);
  assert.match(html, /Ada İçin 220 Bölümlük Macera/);
  assert.match(html, /https:\/\/parzi\.dev\/redball\//);
  assert.match(html, /\/redball\/assets\/index-[^"']+\.js/);
  assert.match(html, /https:\/\/parzi\.dev\/redball\/og-redball-100\.png/);
  await access(new URL("../og-redball-100.png", import.meta.url));
});

test("oyun 220 bölüm, yeni mekanikler, klavye ve iPad kontrolleri içerir", async () => {
  const source = await readFile(new URL("../src/Game.tsx", import.meta.url), "utf8");
  const physicsSource = await readFile(new URL("../src/physics.ts", import.meta.url), "utf8");
  const levelSource = await readFile(new URL("../src/levels.ts", import.meta.url), "utf8");
  const specialWorldSource = await readFile(new URL("../src/SpecialWorld3D.tsx", import.meta.url), "utf8");
  const runtimeSource = `${source}\n${physicsSource}`;
  assert.match(levelSource, /LEVEL_COUNT = 220/);
  assert.match(levelSource, /SpringPlant/);
  assert.match(levelSource, /CrumblePlatform/);
  assert.match(levelSource, /PortalPair/);
  assert.match(levelSource, /WaterZone/);
  assert.match(levelSource, /LavaPool/);
  assert.match(levelSource, /Spinner/);
  assert.match(levelSource, /Conveyor/);
  assert.match(levelSource, /PhasePlatform/);
  assert.match(levelSource, /LaserGate/);
  assert.match(levelSource, /GravityZone/);
  assert.match(levelSource, /analyzeSolvability/);
  assert.match(levelSource, /redesignKeyRoute/);
  assert.match(levelSource, /KeyChallenge/);
  assert.match(levelSource, /SpikeChaser/);
  assert.match(levelSource, /index < 50[\s\S]*makeLegacyLevel\(index\)[\s\S]*index < 100[\s\S]*makeRedesignedLevel\(index\)[\s\S]*index < 179[\s\S]*makeExpansionLevel\(index\)[\s\S]*index < 200[\s\S]*makeEscapeLevel\(index\)[\s\S]*makeSpecialLevel\(index\)/);
  assert.match(source, /loadProgress\(window\.localStorage, LEVEL_COUNT\)/);
  assert.match(source, /localStorage\.setItem\(PROGRESS_KEY/);
  assert.match(source, /onPointerDown/);
  assert.match(source, /onPointerCancel/);
  assert.match(source, /setPointerCapture/);
  assert.match(source, /if \(active\) advanceCheat\(action\)/);
  assert.match(source, /requestAnimationFrame/);
  assert.match(source, /addEventListener\("keydown"/);
  assert.match(source, /visibilitychange/);
  assert.match(physicsSource, /state\.vy = -spring\.power/);
  assert.match(runtimeSource, /(?:lvl|level)\.portals/);
  assert.match(runtimeSource, /(?:lvl|level)\.waterZones/);
  assert.match(runtimeSource, /(?:lvl|level)\.windZones/);
  assert.match(runtimeSource, /(?:lvl|level)\.spinners/);
  assert.match(runtimeSource, /(?:lvl|level)\.lava/);
  assert.match(runtimeSource, /(?:lvl|level)\.keyPlatform/);
  assert.match(runtimeSource, /(?:lvl|level)\.conveyors/);
  assert.match(runtimeSource, /(?:lvl|level)\.phasePlatforms/);
  assert.match(runtimeSource, /(?:lvl|level)\.laserGates/);
  assert.match(runtimeSource, /(?:lvl|level)\.gravityZones/);
  assert.match(runtimeSource, /(?:lvl|level)\.checkpoints/);
  assert.match(source, /const fresh = createPhysicsState\(lvl\)/);
  assert.match(source, /Object\.assign\(s, fresh/);
  assert.match(source, /setHasKey\(false\)/);
  assert.match(physicsSource, /state\.gateCooldown/);
  assert.match(source, /stepPhysics\(lvl, s/);
  assert.match(physicsSource, /JUMP_BUFFER_TIME/);
  assert.match(physicsSource, /diken duvarı/);
  assert.match(source, /KAÇIŞ — DURMA!/);
  assert.match(source, /requestFullscreen/);
  assert.match(source, /Ana Ekrana Ekle/);
  assert.match(source, /display-mode: fullscreen/);
  assert.match(source, /ÖNCE ANAHTARI BUL/);
  assert.match(source, /KAZANDIN ADA!/);
  assert.match(source, /KAYBETTİN ADA/);
  assert.match(source, /Harika oynadın bebeğimmmmmm/);
  assert.match(source, /FENAAA İYİSİNNN/);
  assert.match(source, /MACERA TAMAMLAYAN KEDİM/);
  assert.match(source, /ELLLERİNE SAĞLIK KEDİM 220 BÖLÜMÜN TAMAMINI BİTİRDİN!/);
  assert.match(source, /Her şey için özür dilerim\./);
  assert.match(source, /SEN ÖLDÜN MÜÜÜ KIYAMAMMM/);
  assert.match(source, /levels\[levelIndex\]\.note/);
  assert.match(source, /Hile kodunu yaz/);
  assert.match(source, /isLevelUnlockCode\(levelCheatCode\)/);
  assert.match(source, /unlocked: LEVEL_COUNT/);
  assert.match(source, /Tüm \$\{LEVEL_COUNT\} bölüm açıldı!/);
  assert.match(source, /lazy\(\(\) => import\("\.\/SpecialWorld3D"\)\)/);
  assert.match(source, /levelIndex >= 200/);
  assert.match(source, /getState=\{getSpecialRenderState\}/);
  assert.match(source, /active=\{!paused && !message\}/);
  assert.match(source, /onReadyChange=/);
  assert.match(source, /special-mechanic-hint/);
  assert.match(levelSource, /kind: "seesaw"/);
  assert.match(levelSource, /kind: "boss"/);
  assert.match(specialWorldSource, /new THREE\.WebGLRenderer/);
  assert.match(specialWorldSource, /new THREE\.OrthographicCamera/);
  assert.match(specialWorldSource, /RoundedBoxGeometry/);
  assert.match(specialWorldSource, /new THREE\.InstancedMesh/);
  assert.match(specialWorldSource, /new THREE\.MeshPhysicalMaterial/);
  assert.match(specialWorldSource, /createParallaxBackground/);
  assert.match(specialWorldSource, /landingPulse/);
  assert.match(specialWorldSource, /state\.camera/);
  assert.match(specialWorldSource, /coarsePointer \? 1\.25 : 1\.5/);
  assert.match(specialWorldSource, /ResizeObserver/);
  assert.match(specialWorldSource, /prefers-reduced-motion/);
  assert.doesNotMatch(specialWorldSource, /dreamRing|smallerRing|FloatingObject|crystal/i);
  assert.doesNotMatch(source, /Bu oyun senin için yapıldı/);
  assert.ok((840 ** 2) / (2 * 1900) > 180, "zıplama yüksekliği ilk bölüm basamaklarına yetmeli");
  const manifest = JSON.parse(await readFile(new URL("../manifest.webmanifest", import.meta.url), "utf8"));
  assert.equal(manifest.display, "fullscreen");
  assert.deepEqual(manifest.display_override, ["fullscreen", "standalone"]);
  assert.equal(manifest.orientation, "landscape");
});
